We will go through the different ways to handle errors.

## Usual error experience

Create`app/test/error/page.tsx` :
- This manually throwing an error could’ve been an actual error from sql or anything in your code.
```
export default function Page() {  
    
    // This could be an error from postgres or anything:  
    throw new Error('Lets say there is an error');  
  
    return (  
      <div className="min-h-screen flex items-center justify-center text-center justify-center">  
        Testing error capabilities of NextJS.  
      </div>  
    );  
}
```


The error would be ungraceful. This is a gnarring error message that you probably don’t want users to experience:
![[Pasted image 20250309030539.png]]

## Console error experience

Let’s replace the error with `console.error`:
```
export default function Page() {  
    
    console.error("Lets say there is an error");  
  
    return (  
      <div className="min-h-screen flex items-center justify-center text-center justify-center">  
        Testing error capabilities of NextJS.  
      </div>  
    );  
}
```

The bottom left red error error button is part of NextJS. NextJS listens for `console.error` . The `console.warn`  does NOT trigger the red error button.

![[Pasted image 20250309030607.png]]

Clicking the button would toggle on the previous gnarring error message layout:
![[Pasted image 20250309030622.png]]

Clicking top right “X” will bring back the previous screen with the red error button.

Errors show on both DevTools console and the Terminal console (The terminal that is running the NextJS process):
![[Pasted image 20250309030632.png]]

And:
![[Pasted image 20250309030646.png]]

## Try catch for a more graceful error

But if you had caught it with try-catch and defer it gracefully to only the Devtools console

```
export default function Page() {  
    
    try {  
      // This could be an error from postgres or anything:  
      throw new Error('Lets say there is an error');  
    } catch (error) {  
      console.warn(error);  
    }  
  
    return (  
      <div className="min-h-screen flex items-center justify-center text-center justify-center">  
        Testing error capabilities of NextJS.  
      </div>  
    );  
}
```

By having try-catch with warn, neither the gnarring error layout nor the red button appears.

## error.tsx

The `error.tsx` file defines a UI boundary for a route segment, acting as a catch-all for unexpected errors. It enables you to display a fallback UI to users.  

Create in he same folder an error.tsx, so create
`app/products/[id]/error.tsx` :
```
'use client';  
   
import { useEffect } from 'react';  
   
export default function Error({  
  error,  
  reset,  
}: {  
  error: Error & { digest?: string };  
  reset: () => void;  
}) {  
  useEffect(() => {  
    // Optionally log the error to an error reporting service  
    console.error(error);  
  }, [error]);  
   
  return (  
    <main className="min-h-screen flex flex-col items-flex justify-center text-center pb-24">  
      <h2 className="text-center">Something went wrong!</h2>  
      <button  
        className="mt-4 rounded-md bg-blue-500 px-4 py-2 text-sm text-white transition-colors hover:bg-blue-400 w-fit mx-auto"  
        onClick={  
          // Attempt to recover by trying to re-render the invoices route  
          () => reset()  
        }  
      >  
        Try again  
      </button>  
    </main>  
  );  
}
```

Note that error.tsx doesn’t show from a catch (from try-catch).

If you had changed `test/error/page.tsx` back to:
```
export default function Page() {
  
    throw new Error('Lets say there is an error');

    return (
      <div className="min-h-screen flex items-center justify-center text-center justify-center">
        Testing error capabilities of NextJS.
      </div>
    );
} 
```

Then visiting `localhost:3000/test/error` will show:
![[Pasted image 20250309030801.png]]

A red button also appears because error.tsx will send the error to `console.error` , giving the user the option of viewing the error by clicking the button.

Pressing “Try again” button calls reset(), which refreshes the route
- The `reset()` function is injected by Next.js as a prop when the error boundary is triggered.
- When `reset()` is called, Next.js attempts to re-render the same route without unmounting the entire application. It effectively clears the error state and tries to reload only the affected part of the app.

---


>[!note] Differences to official docs
>
>The official docs have you editing old actions.ts and revisiting old pages. It can get confusing. So I created new pages to demonstrate error handling instead.